config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # nest the review inside the restaurant
  resources :restaurants do
  	collection do
  		get 'search'
  	end
  	resources :reviews, except: [:show, :index]
  end
  get 'pages/about'
  get 'pages/contact'
  root 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

	searchkick
	
	mount_uploader :image, ImageUploader

	has_many :reviews

	validates :name, :address, :phone, :image, presence: true
	validates :phone, format: {
		with: /\A\(\d{3}\) \d{3}-\d{4}\z/,
		message: "must be in the format (123) 456-7890"
	}

	validates :website, format: {
		with: /\Ahttps?:\/\/.*\z/,
		message: "must start with http:// or https://"
	}

	validates :address, format: {
		with: /\A\d+[^,]+,[^,]+, [A-Z]{2} \d{5}\z/,
		message: "must be in the format 3500 Fifth Avenue, New York, NY 10118"
	}
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :restaurant

	validates :rating, :comment, presence: true
	validates :rating, numericality: {
		only_integer: true,
		greater_than_or_equal_to: 1,
		less_than_or_equal_to: 5,
		message: "can only be a whole number between 1 and 5"
	}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 # user can have many reviews, and if user is deleted, all reviews will be deleted
  has_many :reviews, dependent: :destroy

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
		devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :check_user, except: [:index, :show, :search]

  def search
    if params[:search].present?
      @restaurants = Restaurant.search(params[:search])
    else
      @restaurants = Restaurant.all
    end
  end

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @reviews = Review.where(restaurant_id: @restaurant.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: "Sorry, only admins can do that!"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone, :website, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_restaurant
  before_action :check_user, only: [:edit, :update, :destroy]


  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.restaurant_id = @restaurant.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to restaurant_path(@restaurant), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_path(@restaurant), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def check_user
      unless (@review.user == current_user) || (current_user.admin?)
        redirect_to root_url, alert: "Sorry, this review belongs to someone else"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def randomized_background_image
	  images = ["food-1.jpg", "food-2.jpg", "food-3.jpg"]
	  images[rand(images.size)]
	end
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
		return '' if resource.errors.empty?

		message = resource.errors.full_messages.map { |msg| content_tag(:li, msg)}.join
		sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count,
			resource: resource.class.model_name.human.downcase)

		html = <<-HTML
		<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss = "alert">
				<span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span>
			</button>
			<h4 style="font-size:1rem;">#{sentence}</h4>
			#{message}
		</div>
		HTML

		html.html_safe
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_banner.html.erb
<div class="banner">
	<%= image_tag 'logo.png', class: 'banner__img--center', size: "80x40"%>
</div>

app/views/layouts/_bootstrap.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

app/views/layouts/_navbar-small.html.erb
<div class="banner">
	<%= link_to (image_tag 'logo.png', class: 'banner__img--left', size: "80x40"), root_url%>

    <form class="navbar-small__search">
	    <input class="search__input search__input--small" type="search" placeholder="Search" aria-label="Search">
	    <button class="search__btn search__btn--small btn__btn btn__btn--darkred" type="submit">Search</button>
  	</form>

  
  	<div class="navbar-small__btn-group">
  		<% if user_signed_in? %>
          <%= link_to "Profile", edit_user_registration_path, class: "navbar-small__btn btn__link btn__link--red" %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-small__btn btn__link btn__link--white"%>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: "navbar-small__btn btn__link btn__link--red" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "navbar-small__btn btn__link btn__link--white"%>
        <% end %>
  	</div>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">YelpDemo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/pages/about">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/pages/contact">Contact</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/_stylesheet.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


<script src="http://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yelpdemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/stylesheet'%>
  </head>
  <body>
    <div>
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String)  %>
          <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
            <button class="close" type="button" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
              <span class="sr-only">Close</span>
            </button>
            <%= content_tag :div, msg, :id => "flash#(name)"%>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
      <%=image_tag("footer.png", size: "960x140", class:"footer-img")%>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<%= render "layouts/navbar-small" %>
<h1>Welcome to YelpDemo!</h1>
<h2>This is an awesome custom website with the Ruby on Rail programming language.</h2>

app/views/pages/contact.html.erb
<%= render "layouts/navbar-small" %>
<h1>We would love to hear from you!</h1>
<p>Contact me at ziyue.hu1994@gmail.com</p>

app/views/restaurants/_form.html.erb
<%= render "layouts/navbar-small" %>
<div class="form">
  <div class="u-text-centered u-margin-bottom-small">
    <h2 class="form__title">Editing Restaurant</h2>
  </div>
  <%= form_with(model: restaurant, local: true, multipart: true) do |form| %>
  <% if restaurant.errors.any? %>
     <div id="error_explanation" class="alert alert-danger alert-dismissible">
      <button class="close" type="button" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h4>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form__field">
    <%= form.label :name, class:"form__subtitle" %>
    <%= form.text_field :name, class:"form__input", placeholder: "Panda Express" %> 
  </div>

  <div class="form__field">
    <%= form.label :address,class:"form__subtitle" %>
    <%= form.text_field :address, class:"form__input", placeholder: "2100 Gilman Drive, La Jolla, CA 92039" %>
  </div>

  <div class="form__field">
    <%= form.label :phone,class:"form__subtitle" %>
    <%= form.text_field :phone, class:"form__input", placeholder: "(123) 456-789" %>
  </div>

  <div class="form__field">
    <%= form.label :website,class:"form__subtitle" %>
    <%= form.text_field :website, class:"form__input", placeholder: "http://www.pandaexpress.com/"%>
  </div>

  <div class="form__field">
    <%= form.label :image,class:"form__subtitle" %>
    <%= form.file_field :image, class:"form__input"%>
  </div>

  <div class="actions">
    <%= form.submit class: "login-btn btn__btn btn__btn--red u-margin-bottom-smaller"%>
    <%= link_to 'Show', @restaurant, class: "cancel-btn btn__link btn__link--red"%>
    <%= link_to 'Back', restaurants_path, class: "back-btn btn__link btn__link--white"%>
  </div>
<% end %>
</div>
<%= image_tag 'pic-1.png', size:"382x342", class: "right-side-img"%>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<header class="header">
  <div class="navbar">
    <ul class="navbar__nav">
      <li class="navbar__nav-item navbar__left-side">
        <%= link_to "About", pages_about_path, class: "navbar__nav-link" %>
        <%= link_to "Contact", pages_contact_path, class: "navbar__nav-link" %>
      </li>
      <li class="navbar__nav-item navbar__right-side">
        <% if user_signed_in? %>
          <%= link_to "Edit Profile", edit_user_registration_path, class: "navbar__nav-link" %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar__btn btn__link btn__link--white-border"%>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: "navbar__nav-link" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "navbar__btn btn__link btn__link--white-border"%>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="header__logo-box">
    <%=image_tag("logo.png", size: "160x80")%>
  </div>
  <%= form_tag search_restaurants_path, method: :get, class: "search" do %>
    <%= text_field_tag :search, params[:search], class: "search__input"%>
    <%= submit_tag "Search", name: nil, class:"search__btn btn__btn btn__btn--red" %>
  <% end %>
</header>

<h3 class="form__title u-text-centered u-margin-top-small u-margin-bottom-small">Find Best Restaurants in Town</h3>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Restaurant', new_restaurant_path, class: "btn__link btn__link--red new-btn" %>
<% end %>

<div class="cards-list">
  <% @restaurants.each do |restaurant| %>
    <div class="card">
      <% if user_signed_in? && current_user.admin? %>
          <%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn__link btn__link--red-border card__btn-1" %>
          <%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn__link btn__link--red-border card__btn-2" %>
        <% end %>
      <%=image_tag randomized_background_image, class:"card__avatar" %>
      <div class="card__name"><%= link_to restaurant.name, restaurant %></div>
      <div class="card__info"><%= restaurant.phone %></div>
      <div class="card__info"><%= link_to restaurant.website, restaurant.website %></div>
      <div class="card__info"><%= restaurant.address %></div>
    </div>
  <% end %>
</div>


<br>
<script>
  $(function () {
    $(".star-rating").rateYo({
      starWidth: "15px",
      normalFill: "#f1f1f1",
      readOnly:true
    });
  });
</script>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/search.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/show.html.erb
<%= render "layouts/navbar-small" %>

<div class="mycontainer">
  <div class="large-gutters row">
    <div class="col-md-4">
      <h2 class="big-title"><%= @restaurant.name %></h2>
      <div class="star-rating star-rating--inline" data-rateyo-rating= <%= @avg_rating %> ></div>
      <p class="reviews-num"><%= "#{@reviews.length} reviews" %></p>
      <%= image_tag @restaurant.image_url %>
      <div class="summary u-margin-bottom-small u-margin-top-small">
        <ul class="iconed-list">
          <li class="iconed-list__item">
            <div class="iconed-list__avatar"><i class="fas fa-map-marker-alt"></i></div>
            <div class="iconed-list__info"><%= @restaurant.address %></div>
          </li>
          <li class="iconed-list__item">
            <div class="iconed-list__avatar"><i class="fas fa-phone"></i></div>
            <div class="iconed-list__info"> <%= @restaurant.phone %></div>
          </li>
          <li class="iconed-list__item">
            <div class="iconed-list__avatar"><i class="fas fa-globe-americas"></i></div>
            <div class="iconed-list__info last"><%= link_to @restaurant.website, @restaurant.website %></div>
          </li>
        </ul>
      </div>
      <iframe width="330" height="330" frameborder="0" style="border:0"
          src="https://www.google.com/maps/embed/v1/place?&q=<%= @restaurant.address.parameterize %>&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>" allowfullscreen>
      </iframe>
      <%= link_to 'Edit', edit_restaurant_path(@restaurant), class: "edit-btn btn__link btn__link--red" %> 
      <%= link_to 'Back', restaurants_path, class: "back-btn btn__link btn__link--white" %>

    </div>
        <div class="col-md-6 u-margin-top-small">
          <div class="review-btn btn__link btn__link--red u-margin-bottom-small">
            <i class="fas fa-star"></i><%= link_to 'Write a Review', new_restaurant_review_path(@restaurant), class:"style-link"%>
          </div>
          <% if @reviews.blank? %>
            <h3 class="midium-title">No reviews yet, be the first to write one!</h3>
          <% else %>
            <table class="table">
              <thead>
                <tr>
                  <th class="col-name"></th>
                  <th class="col-reviews"></th>
                </tr>
              </thead>
              <tbody>
                <% @reviews.each do |review|%>
                  <tr>
                    <td>
                      <h4>
                        <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
                      </h4>
                      <p><%= review.created_at.strftime("%-m/%-d/%y") %></p>
                    </td>
                    <td>
                       <div class="star-rating" data-rateyo-rating= <%= review.rating %> ></div>
                       <p><%= h(review.comment).gsub(/\n/,'<br/>').html_safe %></p>

                       <% if user_signed_in? %>
                          <% if (review.user == current_user) || (current_user.admin?) %>
                            <%= link_to "Edit", edit_restaurant_review_path(@restaurant,review) %>
                            <%= link_to "Delete", restaurant_review_path(@restaurant, review), method: :delete %>
                          <% end %>
                       <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
        </div>
  </div>
</div>

<script>
  $(function () {
    $(".star-rating").rateYo({
      starWidth: "30px",
      normalFill: "#f1f1f1",
      readOnly:true
    });
  });
</script>

app/views/reviews/_form.html.erb
<%= render "layouts/navbar-small" %>
<div class="form">
  <%= form_with(model: [@restaurant, @review], local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible">
      <button class="close" type="button" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="u-margin-bottom-small">
    <h2 class="form__title">New Review</h2>
  </div>

  <div id="star-rating"></div>

  <div class="form__field">
    <%= form.label :rating,style: "display: none;"%>
    <%= form.number_field :rating, id:"score",style: "display: none;"%>
  </div>

  <div class="form__field">
    <%= form.label :comment, class:"form__subtitle" %> <br />
    <%= form.text_area :comment, placeholder:"How's your experience?", cols:80, rows:10%>
  </div>

  <div class="actions">
    <%= form.submit "Create review", class: "cancel-btn btn__btn btn__btn--red u-margin-bottom-smaller"%>
    <%= link_to 'Back', restaurant_path(@restaurant), class: "back-btn btn__link btn__link--white u-margin-bottom-smaller"%>
  </div>
<% end %>
</div>



<script>
  $(function () {
    var score;
    $("#star-rating").rateYo({
      starWidth: "30px",
      normalFill: "#f1f1f1",
      fullStar: true,
      onSet: function (rating, rateYoInstance) {
        $("#score").val(rating);
      }
    });
  });
</script>

app/views/reviews/edit.html.erb
<%= render 'form', review: @review %>

app/views/reviews/new.html.erb
<%= render 'form', review: @review %>